---
heat_template_version: 2015-10-15
description: "Kubernetes Lab"

parameters:

  worker_node_count:
    label: "Worker Node Count"
    description: "Worker Node Count"
    type: number
    default: 2

  lab_repo:
    label: "Lab Repo"
    description: "Lab Repo"
    type: string
    default: "https://github.com/NeCTAR-RC/lab-kubernetes.git"

  lab_repo_version:
    label: "Lab Repo Version"
    description: "Lab Repo Version"
    type: string
    default: "master"

  availability_zone:
    label: "Availability Zone"
    description: "The availability zone for resources to be created in"
    type: string
    default: ""

resources:

  prefix:
    type: OS::Heat::TestResource
    properties:
      value: { get_param: "OS::stack_name" }

  password:
    type: OS::Heat::RandomString
    properties:
      length: 8
      sequence: lettersdigits

  keypair:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name:
        str_replace:
          template: "%prefix%-keypair"
          params:
            "%prefix%": { get_attr: [prefix, output] }

  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: "%prefix%-secgroup"
          params:
            "%prefix%": { get_attr: [prefix, output] }

  master_secgroup_rules:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: "%prefix%-secgroup-master"
          params:
            "%prefix%": { get_attr: [prefix, output] }
      rules:
        - remote_group_id: { get_resource: secgroup }
          remote_mode: remote_group_id
          protocol: tcp
          port_range_min: 1
          port_range_max: 65535

        - remote_group_id: { get_resource: secgroup }
          remote_mode: remote_group_id
          protocol: udp
          port_range_min: 1
          port_range_max: 65535

        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22

        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443

        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  worker_secgroup_rules:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: "%prefix%-secgroup-worker"
          params:
            "%prefix%": { get_attr: [prefix, output] }
      rules:
        - remote_group_id: { get_resource: secgroup }
          remote_mode: remote_group_id
          protocol: tcp
          port_range_min: 1
          port_range_max: 65535

        - remote_group_id: { get_resource: secgroup }
          remote_mode: remote_group_id
          protocol: udp
          port_range_min: 1
          port_range_max: 65535

        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  server_master_node:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "%prefix%-master"
          params:
            "%prefix%": { get_attr: [prefix, output] }
      flavor: "m2.small"
      image: "NeCTAR Ubuntu 16.04 LTS (Xenial) amd64"
      admin_pass: { get_resource: password }
      key_name: { get_resource: keypair }
      availability_zone: { get_param: availability_zone }
      security_groups: [ { get_resource: secgroup }, { get_resource: master_secgroup_rules } ]
      networks:
        - { uuid: 00000000-0000-0000-0000-000000000000 }
      user_data_format: RAW
      user_data: { get_resource: cloud_config }

  server_worker_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: worker_node_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name:
            str_replace:
              template: "%prefix%-worker-%index%"
              params:
                "%prefix%": { get_attr: [prefix, output] }
          flavor: "m2.small"
          image: "NeCTAR Ubuntu 16.04 LTS (Xenial) amd64"
          admin_pass: { get_resource: password }
          key_name: { get_resource: keypair }
          availability_zone: { get_param: availability_zone }
          security_groups: [ { get_resource: secgroup }, { get_resource: worker_secgroup_rules } ]
          networks:
            - { uuid: 00000000-0000-0000-0000-000000000000 }
          user_data_format: RAW
          user_data: { get_resource: cloud_config }

  swift_signal_handle:
    type: OS::Heat::SwiftSignalHandle

  swift_signal:
    type: OS::Heat::SwiftSignal
    properties:
      handle: { get_resource: swift_signal_handle }
      count: 1
      timeout: 14400

  cloud_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        disable_root: false
        system_info:
          default_user:
            lock_passwd: False
        ssh_pwauth: yes
        password: { get_resource: password }
        chpasswd:
          expire: false
        packages:
          - vim

  cloud_config_ansible:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        system_info:
          default_user:
            lock_passwd: False
        ssh_pwauth: yes
        password: { get_resource: password }
        chpasswd:
          expire: false
        bootcmd:
          - sleep 15
        packages:
          - ansible
          - tmux
          - multitail
          - git
          - gcc
          - make
          - libssl-dev
          - libffi-dev
          - python-dev
          - python-virtualenv
          - vim
        write_files:
          - path: "/etc/apt/preferences.d/backports.pref"
            content: |
              Package: ansible
              Pin: release a=xenial-backports
              Pin-Priority: 500
          - path: "/opt/cloud-training/id_rsa"
            permissions: "0600"
            content: { get_attr: [keypair, private_key] }
          - path: "/opt/cloud-training/hosts.j2"
            permissions: "0600"
            content: |
              [all]
              master ansible_ssh_host={{ master_node_ip_address }} ansible_user=ubuntu
              {% for worker_node_ip_address in worker_nodes_ip_address %}
              worker-{{ loop.index0 }} ansible_ssh_host={{ worker_node_ip_address }} ansible_user=ubuntu
              {% endfor %}
              
              [master]
              master
              
              [worker]
              {% for worker_node_ip_address in worker_nodes_ip_address %}
              worker-{{ loop.index0 }}
              {% endfor %}
          - path: "/opt/cloud-training/environment.yaml"
            permissions: "0600"
            content:
              str_replace:
                template: |
                  ---
                  master_node_ip_address: "%master_node_ip_address%"
                  worker_nodes_ip_address: %worker_nodes_ip_address%
                params:
                  "%master_node_ip_address%": { get_attr: [server_master_node, accessIPv4] }
                  "%worker_nodes_ip_address%": { get_attr: [server_worker_nodes, accessIPv4] }
          - path: "/opt/cloud-training/runcmd-bash"
            permissions: "0700"
            content:
              str_replace:
                template: |
                  #!/bin/bash
                  export HOME="/root"
                  set -e
                  set -x
                  function exit_failure {
                    %swift_signal_notify% --data-binary '{"status": "FAILURE", "reason": "'"$@"'"}'
                    exit 1
                  }
                  function exit_success {
                    %swift_signal_notify% --data-binary '{"status": "SUCCESS"}'
                  }
                  git clone %lab_repo% /opt/cloud-training/lab || exit_failure "Git Clone - %lab_repo%"
                  cd /opt/cloud-training/lab
                  git checkout %lab_repo_version% || exit_failure "Git Checkout - %lab_repo_version%"
                  cd /opt/cloud-training/lab/ansible
                  ansible localhost -e @/opt/cloud-training/environment.yaml -m template -a "src=/opt/cloud-training/hosts.j2 dest=/opt/cloud-training/hosts" || exit_failure "Ansible Inventory Template"
                  ansible-playbook playbook.yaml -vv || exit_failure "Ansible Playbook run failed"
                  exit_success
                params:
                  "%swift_signal_notify%": { get_attr: [swift_signal_handle, curl_cli] }
                  "%lab_repo%": { get_param: lab_repo }
                  "%lab_repo_version%": { get_param: lab_repo_version }
        runcmd:
          - tmux new-session -s runcmd -n runcmd-bash -d
          - tmux new-window -n runcmd-bash-logs
          - tmux select-window -t runcmd-bash-logs
          - tmux send-keys "touch /opt/cloud-training/runcmd-bash.err /opt/cloud-training/runcmd-bash.log" C-m
          - tmux send-keys "multitail /opt/cloud-training/runcmd-bash.err /opt/cloud-training/runcmd-bash.log" C-m
          - tmux select-window -t runcmd-bash
          - tmux send-keys "/opt/cloud-training/runcmd-bash >> /opt/cloud-training/runcmd-bash.log 2>> /opt/cloud-training/runcmd-bash.err" C-m
          - tmux select-window -t runcmd-bash-logs

  server_ansible:
    depends_on:
      - server_master_node
      - server_worker_nodes
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "%prefix%-ansible"
          params:
            "%prefix%": { get_attr: [prefix, output] }
      flavor: "m2.xsmall"
      image: "NeCTAR Ubuntu 16.04 LTS (Xenial) amd64"
      admin_pass: { get_resource: password }
      key_name: { get_resource: keypair }
      availability_zone: { get_param: availability_zone }
      security_groups: [ { get_resource: secgroup }, { get_resource: master_secgroup_rules } ]
      networks:
        - { uuid: 00000000-0000-0000-0000-000000000000 }
      config_drive: True
      user_data_format: RAW
      user_data: { get_resource: cloud_config_ansible }

outputs:

  password:
    description: "Password"
    value: { get_resource: password }

  private_key:
    description: "Private Key"
    value: { get_attr: [keypair, private_key] }

  ansible_ip_address:
    description: "Ansible IP Address"
    value: { get_attr: [server_ansible, accessIPv4] }

  master_node_ip_address:
    description: "Master Node IP Address"
    value: { get_attr: [server_master_node, accessIPv4] }

  worker_nodes_ip_address:
    description: "Worker Nodes IP Address"
    value: { get_attr: [server_worker_nodes, accessIPv4] }
